[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 79

[tool.flake8]
max-line-length = 79
exclude = ["__pycache__", ".git", ".gitignore"]
# ignore = ["E203", "W503"]

[tool.pylint]
max-line-length = 79
exclude = ["__pycache__", ".git"]
# disable = ["C0111", "R0915"]
